[package]
name = "smtpbis"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]
edition = "2018"
description = "Asynchronous ESMTP service library."
license = "GPL-3.0+"
categories = ["email", "network-programming"]
readme = "README.md"

[dependencies]
rustyknife = {git="https://github.com/zerospam/rustyknife.git", rev="master", default_features=false, features=["quoted-string-rfc2047"]}
tokio = {version="=0.2.0-alpha.3", features=["signal"]}
bytes = "0.4.12"
futures-util-preview = "0.3.0-alpha.18"
tokio-rustls = "0.12.0-alpha.1"
nom = "5.0"
async-trait = "0.1.10"
