[package]
name = "smtpbis"
version = "0.1.5"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]
edition = "2018"
description = "Asynchronous ESMTP service library."
license = "GPL-3.0+"
categories = ["email", "network-programming"]
readme = "README.md"
homepage = "https://github.com/zerospam/smtpbis"
repository = "https://github.com/zerospam/smtpbis.git"

[dependencies]
rustyknife = {version="0.2", features=["quoted-string-rfc2047"]}
tokio = {version="0.2", features=["signal", "io-util", "sync", "signal", "rt-core", "tcp", "dns", "rt-threaded"]}
tokio-util = {version="0.3", features=["codec"]}
bytes = "0.5"
futures = "0.3"
futures-util = "0.3"
tokio-rustls = "0.13"
nom = "5.1"
async-trait = "0.1.10"
